version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mottu-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mottu_backend
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-setup.js:/docker-entrypoint-initdb.d/mongodb-setup.js:ro
    networks:
      - mottu-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mottu-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - mottu-network

volumes:
  mongodb_data:

networks:
  mottu-network:
    driver: bridge
